version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
