services:
  - type: web
    name: backend
    env: node
    dockerfilePath: ./backend/Dockerfile
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
    plan: starter
    healthCheckPath: "/health"

  - type: web
    name: frontend
    env: static
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: "npm run build"
    startCommand: "serve -s build -l 80"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://<backend-service-name>.onrender.com"
    plan: starter
