services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 5000
